moose_petsc:
  - moose-petsc 3.20.3 build_2

moose_libmesh_vtk:
  - moose-libmesh-vtk 9.2.6 build_10

#### Darwin SDK SYSROOT
CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/MacOSX11.3.sdk                                     # [osx]

MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 11.3                                                    # [osx]
