moose_dev:
  - moose-dev 2024.05.20

#### Darwin SDK SYSROOT
CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/MacOSX11.3.sdk                                     # [osx]

MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 11.3                                                    # [osx]
