moose_wasp:
  moose-wasp 2024.05.20

moose_python:
  - python 3.10
  - python 3.9
  - python 3.8

# Pesky packages that break internal CI
# Note: Modifying/Updating this will require changes to conda/mpich!
setuptools:
  - <60.0
pin_run_as_build:
  setuptools: x.x

#### Darwin SDK SYSROOT
CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/MacOSX11.3.sdk                                     # [osx]

MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 11.3                                                    # [osx]
