Content:
    - framework/doc/content
    - modules/fluid_properties/doc/content
    air:
        root_dir: ${MOOSE_DIR}/modules/fluid_properties/contrib/air/doc/content
    carbon_dioxide:
        root_dir: ${MOOSE_DIR}/modules/fluid_properties/contrib/carbon_dioxide/doc/content
    helium:
        root_dir: ${MOOSE_DIR}/modules/fluid_properties/contrib/helium/doc/content
    nitrogen:
        root_dir: ${MOOSE_DIR}/modules/fluid_properties/contrib/nitrogen/doc/content
    potassium:
        root_dir: ${MOOSE_DIR}/modules/fluid_properties/contrib/potassium/doc/content
    sodium:
        root_dir: ${MOOSE_DIR}/modules/fluid_properties/contrib/sodium/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: MOOSE Fluid Properties Module
        repo: https://github.com/idaholab/moose
        home: /modules/fluid_properties/index.md
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/fluid_properties
        remove:
            framework: !include framework/doc/remove.yml
            fluid_properties: !include modules/fluid_properties/doc/remove.yml
        unregister:
            framework: !include framework/doc/unregister.yml
        includes:
            - framework/include
            - modules/fluid_properties/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
    MooseDocs.extensions.template:
        active: True
    MooseDocs.extensions.sqa:
        active: True
        reports: !include modules/fluid_properties/doc/sqa_reports.yml
        categories:
            framework: !include framework/doc/sqa_framework.yml
            fluid_properties: !include modules/fluid_properties/doc/sqa_fluid_properties.yml
            air: !include modules/fluid_properties/contrib/air/doc/sqa_air.yml
            carbon_dioxide: !include modules/fluid_properties/contrib/carbon_dioxide/doc/sqa_carbon_dioxide.yml
            helium: !include modules/fluid_properties/contrib/helium/doc/sqa_helium.yml
            nitrogen: !include modules/fluid_properties/contrib/nitrogen/doc/sqa_nitrogen.yml
            potassium: !include modules/fluid_properties/contrib/potassium/doc/sqa_potassium.yml
            sodium: !include modules/fluid_properties/contrib/sodium/doc/sqa_sodium.yml
